<a href="https://colab.research.google.com/github/chandrakant1212/Descriptive-Statistivs-and-EDA/blob/main/Naive_Bayes_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Tasks to Perform**

- **Understand the Problem and Setup**: Define objectives, install/import required libraries, and set up the environment for the task.

- **Load and Inspect Data**: Load datasets, inspect their structure, and understand the data's format, columns, and types.

- **Clean the Data**: Handle missing, duplicate, or inconsistent values, and correct data types.

- **Conduct Exploratory Data Analysis (EDA)**: Summarize data with statistical and visual tools like histograms, heatmaps, and pair plots to explore patterns and relationships.

- **Train Models**: Select and train appropriate machine learning models for the task (Naïve Bayes Classification).

- **Evaluate and Interpret**: Evaluate model performance using the score method, which calculates the percentage of correct predictions.

- **Report and Document**: Note down observations/insights found during the implementation process.

---

### **NOTE**
- The steps provided are a general guide and not mandatory; adapt them based on the given problem statement, business case, requirements, and data.  
- Focus on understanding the problem and performing only the relevant tasks to achieve the objective efficiently.

## Problem Statement
The objective is to develop a classification model using Naïve Bayes to predict whether a person earns over 50K annually based on their demographic and employment-related attributes.  

The goal is to assist in understanding factors influencing income classification and provide insights for socio-economic research and policy-making.

## Features in Dataset
The dataset contains the following features:

- **id**: Unique identifier for the individual.  
- **age**: Age of the individual.  
- **workclass**: Type of employment (e.g., Private, Self-Employed).  
- **education**: Level of education (e.g., Bachelors, Masters).  
- **education-num**: Number of years of education completed.  
- **marital-status**: Marital status of the individual.  
- **occupation**: Type of job (e.g., Tech-support, Craft-repair).  
- **relationship**: Family relationship (e.g., Husband, Wife).  
- **race**: Race of the individual.  
- **sex**: Gender of the individual.  
- **capital-gain**: Income from investment gains.  
- **capital-loss**: Income lost from investments.  
- **hours-per-week**: Number of hours worked per week.  
- **native-country**: Country of origin.  
- **income**: Target variable, whether the individual earns ">50K" or "<=50K".

---

## Output Format
The final output should be a dataframe of predictions on the `test_data` (provided to you).  

It should consist of two columns:  
- **id**: Identifier from the test data.  
- **income**: Predicted income class.  

### Sample Output:
|   id   |   income   |
|--------|------------|
|  107   |   0     |
|  110 |   1     |
|  117 |   0     |
|  118 |   0     |
|  120   |   1     |

## Metrics on Evaluation
Your submission will be evaluated using the **score method**, which calculates the percentage of correct predictions in the test dataset.

---

## Completion Criteria
Your submission will be considered valid if:
- You achieve an accuracy score of more than eg: 70% on the test set.

## Import Required Libraries

In [29]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
import warnings

warnings.filterwarnings('ignore')


# add more libraries accordingly

## Load Data
- Do not modify the given code. Execute the below code cells sequencially to get the data.

In [30]:
# Load the data
train_data_url = "https://new-assets.ccbp.in/frontend/content/aiml/classical-ml/adult_dataset.csv"
test_data_url = "https://new-assets.ccbp.in/frontend/content/aiml/classical-ml/adult_test_data.csv"

In [31]:
train_data = pd.read_csv(train_data_url)
test_data = pd.read_csv(test_data_url)

In [32]:
train_data.head()

,id,age,workcalss,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,101,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,102,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,103,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,104,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,105,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0

In [33]:
test_data.head()

,id,age,workcalss,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,107,49,Private,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica
1,110,42,Private,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States
2,117,25,Self-emp-not-inc,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States
3,118,32,Private,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States
4,120,43,Self-emp-not-inc,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States

## Implementation
- Write the code in the provided code cells. Create new code cells if required.
- Build the Naïve Bayes model using the provided `train_data`. Import and use the appropriate libraries required for building the model.
- Evaluate the model on `test_data` and generate the predictions.
- Build a Naive Bayes model which calculates the percentage of correct predictions in the test dataset.

In [34]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
vectorizer.fit(train_data)
vectorizer.vocabulary_

{'id': 6,
 'age': 0,
 'workcalss': 19,
 'education': 3,
 'num': 11,
 'marital': 9,
 'status': 17,
 'occupation': 12,
 'relationship': 15,
 'race': 14,
 'sex': 16,
 'capital': 1,
 'gain': 4,
 'loss': 8,
 'hours': 5,
 'per': 13,
 'week': 18,
 'native': 10,
 'country': 2,
 'income': 7}

In [35]:
vocab_dict = vectorizer.vocabulary_.copy()
dict(sorted(vocab_dict.items(),key=lambda x:x[1]))

{'age': 0,
 'capital': 1,
 'country': 2,
 'education': 3,
 'gain': 4,
 'hours': 5,
 'id': 6,
 'income': 7,
 'loss': 8,
 'marital': 9,
 'native': 10,
 'num': 11,
 'occupation': 12,
 'per': 13,
 'race': 14,
 'relationship': 15,
 'sex': 16,
 'status': 17,
 'week': 18,
 'workcalss': 19}

In [36]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25761 entries, 0 to 25760
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              25761 non-null  int64
 1   age             25761 non-null  int64
 2   workcalss       25761 non-null  object
 3   education       25761 non-null  object
 4   education-num   25761 non-null  int64
 5   marital-status  25761 non-null  object
 6   occupation      25761 non-null  object
 7   relationship    25761 non-null  object
 8   race            25761 non-null  object
 9   sex             25761 non-null  object
 10  capital-gain    25761 non-null  int64
 11  capital-loss    25761 non-null  int64
 12  hours-per-week  25761 non-null  int64
 13  native-country  25761 non-null  object
 14  income          25761 non-null  int64
dtypes: int64(7), object(8)
memory usage: 2.9+ MB

In [37]:
train_data.isna().sum()

id                0
age               0
workcalss         0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

In [38]:
categorical_cols = ['workcalss', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']

for col in categorical_cols:
    le = LabelEncoder()
    train_data[col] = le.fit_transform(train_data[col])



    test_data[col] = le.transform(test_data[col])

In [39]:
X = train_data.drop(columns=['id','income']).copy()
y = train_data['income']
print(f'Shape of X: {X.shape}')

Shape of X: (25761, 13)

In [40]:
X.shape, y.shape

((25761, 13), (25761,))

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [42]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((20608, 13), (5153, 13), (20608,), (5153,))

## Build Naive Bayes Model

In [43]:
nb = GaussianNB()
nb.fit(X_train, y_train)

GaussianNB()

In [44]:
train_score = nb.score(X_train, y_train)
test_score = nb.score(X_test, y_test)
print("Training Accuracy: {:.2f}, Testing Accuracy: {:.2f}".format(train_score, test_score))

Training Accuracy: 0.80, Testing Accuracy: 0.81

## Your Final Submission
### Instructions  

1. **Write Your Solution in the Provided Code Cell**  
   - Use the code cell provided below for your final solution.  
   - **Do not delete** this code cell or create a new one.  

2. **Avoid Creating New Cells**  
   - If you delete the provided code cell and create a new one to write your code, it will not be evaluated.  
   - In such cases, you will need to create a new copy of the notebook from the platform and re-write your code.  

3. **Follow a Step-by-Step Approach**  
   - Merge your solution step-by-step in the provided code cell:  
     - Start by importing the required libraries.  
     - Load the data.  
     - Perform data pre-processing.  
     - Split the data into training and testing sets.  
     - Build the model.  
     - Evaluate the model.  
   - Ensure the steps are followed in a proper sequence for clarity and correctness.

In [45]:
# Write your final code here as per the instructions
# Create a dataframe of test predictions (ID, Class)
submission_df = pd.DataFrame(columns=['id', 'income'])
submission_df['id'] = test_data['id']
# Ensure test data for prediction has the same features and order as X_train
submission_df['income'] = nb.predict(test_data[X.columns])
submission_df.head()

    id  income
0  107       0
1  110       1
2  117       0
3  118       0
4  120       0