<a href="https://colab.research.google.com/github/chandrakant1212/Descriptive-Statistivs-and-EDA/blob/main/Pandas_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Assignment

## Instructions for Pandas Assignment
---
Welcome to the Pandas Assignment! In this exercise, you will work with the CO2_Emissions_Canada2 dataset for Assignment your data manipulation and analysis skills using Pandas. Please follow the instructions below carefully:

1. **Understand the Dataset**: The dataset used in this assignment is related to the CO2_Emissions_Canada2. Familiarize yourself with the dataset's structure and content before starting.

2. **Read Each Question Thoroughly**: Each question in this assignment is designed to test different Pandas functionalities. Make sure you understand the requirements of each question before you begin coding.

3. **Write Your Code in the Provided Cells**: For each question, a code cell is provided where you should write your solution. Do not modify any other cells or sections of the notebook.

4. **Execute Your Code**: After writing your code in each cell, run the cell to check if your code produces the expected results. Verify that the output matches the requirements specified in the question.

5. **Complete All Questions**: Ensure that you attempt and complete all the questions provided in the notebook. Each question is designed to test different Pandas skills and concepts.

6. **Review Your Work**: Before submitting, double-check your answers and make sure all questions are addressed. Ensure that the notebook runs without errors and that all outputs are correct.

7. **Download Your Notebook**: Once you have completed all the questions and verified your solutions, download the notebook file (.ipynb). You can do this by selecting `File` > `Download` > `Download .ipynb` from the Google Colab menu.

8. **Submit Your Assignment**: Upload the downloaded .ipynb file to the designated learning platform for submission.

9. **Verify Submission**: Ensure that you have uploaded the correct file and that it is not corrupted. If you encounter any issues with the file, you may need to resubmit.

---

Good luck with your Assignment!

In [2]:
import numpy as np
import pandas as pd

co2_emission = "https://s3.ap-south-1.amazonaws.com/new-assets.ccbp.in/frontend/content/aiml/classical-ml/CO2_Emissions_Canada2.csv"

data = pd.read_csv(co2_emission)
data.head()

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196.0
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221.0
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136.0
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255.0
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244.0

**Q. 1 Determine the total number of vehicles for each `fuel type` available in the dataset.**

In [7]:
# write your code here
fuel_type_count = data.groupby('Fuel Type')['Vehicle Class'].count()
fuel_type_count

Fuel Type
D     175
E     370
N       1
X    3637
Z    3202
Name: Vehicle Class, dtype: int64

**Q. 2 Find the proportion of vehicles with CO2 emissions greater than 250 g/km. Output should be in the given format of 2 decimals :- Proportion of high CO2 emission vehicles: ___**

In [10]:
# write your code here
# write your code here
total_vehicles = len(data)
high_emission_vehicles = data[data['CO2 Emissions(g/km)'] > 250]
proportion = len(high_emission_vehicles) / total_vehicles
proportion_formatted = "{:.2f}".format(proportion)
print(f"Proportion of high CO2 emission vehicles: {proportion_formatted}")

Proportion of high CO2 emission vehicles: 0.47

**Q. 3 Identify which car manufacturers have above-average fuel consumption compared to all manufacturers.**

In [11]:
# write your code here
#Calculate the mean of "Fuel Consumption Comb (L/100 km)" across all rows in the DataFrame
avg_consumption = data['Fuel Consumption Comb (L/100 km)'].mean()

# Filter the DataFrame to only those rows where fuel consumption is greater than the average
# and then extract the unique vehicle makes that meet this criterion
above_avg_fuel_comsumption = data[data['Fuel Consumption Comb (L/100 km)'] > avg_consumption]['Make'].unique()
above_avg_fuel_comsumption

array(['ACURA', 'ASTON MARTIN', 'AUDI', 'BENTLEY', 'BMW', 'BUICK',
       'CADILLAC', 'CHEVROLET', 'CHRYSLER', 'DODGE', 'FORD', 'GMC',
       'HONDA', 'HYUNDAI', 'INFINITI', 'JAGUAR', 'JEEP', 'KIA',
       'LAMBORGHINI', 'LAND ROVER', 'LEXUS', 'LINCOLN', 'MASERATI',
       'MAZDA', 'MERCEDES-BENZ', 'MITSUBISHI', 'NISSAN', 'PORSCHE', 'RAM',
       'ROLLS-ROYCE', 'SRT', 'SUBARU', 'TOYOTA', 'VOLKSWAGEN', 'VOLVO',
       'ALFA ROMEO', 'GENESIS', 'BUGATTI'], dtype=object)

---
**Q. 4 What is the most common combination of vehicle class and transmission type along with its average fuel consumption?** In the given format ( The most common combination is ______ with an average fuel consumption of __ )

In [13]:
from re import M
from os import posix_spawn
# Get the most common vehicle class and transmission type combination
most_common_combination = data.groupby(['Vehicle Class', 'Transmission']).size().idxmax()

# Get the average fuel consumption for the most common combination
filtered_data = data[(data['Vehicle Class'] == most_common_combination[0]) &
                     (data['Transmission'] == most_common_combination[1])]
fuel_consumption_value = filtered_data['Fuel Consumption Comb (L/100 km)'].mean()

print(f"The most common combination is {most_common_combination[0]} {most_common_combination[1]} with an average fuel consumption of {fuel_consumption_value:.2f}")

The most common combination is SUV - SMALL AS6 with an average fuel consumption of 10.15

**Q. 5 Determine which combination of engine size and fuel type results in the highest average CO2 emissions.**

In [16]:
# Group the data by 'Engine size' and 'Fuel Type', then calculate the mean of 'CO2 Emissions(g/km)' for each group.
# Sort the resulting mean values in descending order to show which combinations of engine size and fuel types have the highest average CO2 emissions.

highest_avg_co2 = data.groupby(['Engine Size(L)', 'Fuel Type'])['CO2 Emissions(g/km)'].mean().sort_values(ascending=False).idxmax()
highest_avg_co2

(np.float64(8.0), 'Z')

---
**Q. 6 What is the range of fuel consumption (L/100 km) for vehicles in the "MID-SIZE" class?**

In [17]:
# write your code here
# Extract only the CO2 emissions from rows where the 'Vehicle Class' is 'MID-SIZE'
mid_size_filtered_data =  data[data['Vehicle Class'] == 'MID-SIZE']


# Calculate the range of CO2 emissions by subtracting the minimum value from the maximum value
co2_range = mid_size_filtered_data['Fuel Consumption Comb (L/100 km)'].max()
co2_range

20.0

**Q. 7 Find the value between (maximum - minimum) of CO2 emissions vehicle class compact in the dataset.**

In [18]:
# write your code here
# Extract only the CO2 emissions from rows where the 'Vehicle Class' is 'MID-SIZE'
mid_size = data[data['Vehicle Class'] == 'COMPACT']

# Calculate the range of CO2 emissions by subtracting the minimum value from the maximum value
co2_range = mid_size['CO2 Emissions(g/km)'].max() - mid_size['CO2 Emissions(g/km)'].min()
co2_range

298.0

**Q. 8 Analyze whether there is a correlation between fuel consumption (combined) and CO2 emissions.**

In [19]:
# write your code here and find the correlation coefficient between the two columns.
correlation = data['Fuel Consumption Comb (L/100 km)'].corr(data['CO2 Emissions(g/km)'])
correlation

np.float64(0.9180169584984268)

**Q. 9 Find the top 5 vehicles with the highest fuel consumption in the city (L/100 km).**

In [20]:
# Sort by 'Fuel Consumption City (L/100 km)' in descending order and select top 5
top_fuel_consumers = data.sort_values(by='Fuel Consumption City (L/100 km)', ascending=False).head(5)
top_fuel_consumers

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
1534,GMC,SAVANA 3500 PASSENGER FFV,VAN - PASSENGER,6.0,8,A6,E,30.6,20.6,26.1,11,418.0
1329,CHEVROLET,EXPRESS 3500 PASSENGER FFV,VAN - PASSENGER,6.0,8,A6,E,30.6,20.6,26.1,11,418.0
1530,GMC,SAVANA 2500 PASSENGER FFV,VAN - PASSENGER,6.0,8,A6,E,30.3,20.5,25.9,11,414.0
1325,CHEVROLET,EXPRESS 2500 PASSENGER FFV,VAN - PASSENGER,6.0,8,A6,E,30.3,20.5,25.9,11,414.0
228,CHEVROLET,EXPRESS 3500 PASSENGER,VAN - PASSENGER,6.0,8,A6,E,30.2,20.5,25.8,11,413.0

**Q. 10 Filter all vehicles that have 4 cylinders and CO2 emissions less than 200 g/km.**

In [22]:
# Filter vehicles with 4 cylinders and CO2 emissions less than 200
filtered_vehicles = data[(data['Cylinders'] == 4) & (data['CO2 Emissions(g/km)'] < 200)]
filtered_vehicles

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196.0
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136.0
12,ALFA ROMEO,4C,TWO-SEATER,1.8,4,AM6,Z,9.7,6.9,8.4,34,193.0
76,BMW,320i,COMPACT,2.0,4,A8,Z,10.0,6.5,8.4,34,193.0
79,BMW,328d xDRIVE,COMPACT,2.0,4,A8,D,7.6,5.5,6.7,42,181.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7363,VOLKSWAGEN,Golf,COMPACT,1.4,4,M6,X,8.4,6.6,7.6,37,177.0
7366,VOLKSWAGEN,Jetta,COMPACT,1.4,4,AS8,X,7.8,5.9,7.0,40,162.0
7367,VOLKSWAGEN,Jetta,COMPACT,1.4,4,M6,X,7.9,5.9,7.0,40,163.0
7368,VOLKSWAGEN,Jetta GLI,COMPACT,2.0,4,AM7,X,9.3,7.2,8.4,34,196.0
7369,VOLKSWAGEN,Jetta GLI,COMPACT,2.0,4,M6,X,9.6,7.1,8.5,33,198.0

**Q. 11 Find the most common fuel type and its frequency. In the given format (The most common fuel type is __ with a frequency of _____)**

In [23]:
# Find the most common fuel type and its count
most_common_fuel_type = data['Fuel Type'].value_counts().idxmax()
fuel_type_count = data['Fuel Type'].value_counts().max()
print(f"The most common fuel type is {most_common_fuel_type} with a frequency of {fuel_type_count}")

The most common fuel type is X with a frequency of 3637

**Q. 12 Replace missing values in the dataset with the column mean for numeric columns.**

In [26]:
# Fill NaN values with the mean for numeric columns
numeric_cols = data.select_dtypes(include=np.number).columns
data_filled = data.copy()
data_filled[numeric_cols] = data_filled[numeric_cols].fillna(data_filled[numeric_cols].mean())

# Verify no NaN remains
print(data_filled.isnull().sum())
data_filled

Make                                0
Model                               0
Vehicle Class                       0
Engine Size(L)                      0
Cylinders                           0
Transmission                        0
Fuel Type                           0
Fuel Consumption City (L/100 km)    0
Fuel Consumption Hwy (L/100 km)     0
Fuel Consumption Comb (L/100 km)    0
Fuel Consumption Comb (mpg)         0
CO2 Emissions(g/km)                 0
dtype: int64

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196.0
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221.0
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136.0
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255.0
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219.0
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232.0
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240.0
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232.0
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248.0

**Q. 13 Find the make and model of the vehicle with the highest CO2 emissions.**

In [27]:
# Find the vehicle with the highest CO2 emissions
max_emission_vehicle = data[data['CO2 Emissions(g/km)'] == data['CO2 Emissions(g/km)'].max()]
max_emission_vehicle

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
4509,BUGATTI,CHIRON,TWO-SEATER,8.0,16,AM7,Z,26.8,16.6,22.2,13,522.0
5575,BUGATTI,Chiron,TWO-SEATER,8.0,16,AM7,Z,26.8,16.6,22.2,13,522.0
6640,BUGATTI,Chiron,TWO-SEATER,8.0,16,AM7,Z,26.8,16.6,22.2,13,522.0

**Q. 14 Filter vehicles with engine size greater than the average engine size and sort them by CO2 emissions (descending).**

In [29]:
# Filter vehicles with engine size greater than the average and sort by CO2 emissions
avg_engine_size = data['Engine Size(L)'].mean()
filtered_sorted_vehicles = data[data['Engine Size(L)'] > avg_engine_size].sort_values(by='CO2 Emissions(g/km)', ascending=False)
filtered_sorted_vehicles

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
5575,BUGATTI,Chiron,TWO-SEATER,8.0,16,AM7,Z,26.8,16.6,22.2,13,522.0
4509,BUGATTI,CHIRON,TWO-SEATER,8.0,16,AM7,Z,26.8,16.6,22.2,13,522.0
6640,BUGATTI,Chiron,TWO-SEATER,8.0,16,AM7,Z,26.8,16.6,22.2,13,522.0
6046,LAMBORGHINI,Aventador Roadster,TWO-SEATER,6.5,12,AM7,Z,26.6,15.8,21.7,13,493.0
7059,LAMBORGHINI,Aventador Roadster,TWO-SEATER,6.5,12,AM7,Z,26.6,15.8,21.7,13,493.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1763,LEXUS,GS 450h,MID-SIZE,3.5,6,AV8,Z,8.0,6.9,7.5,38,172.0
1633,INFINITI,Q70 HYBRID,MID-SIZE,3.5,6,AS7,Z,8.0,6.9,7.5,38,172.0
1622,INFINITI,Q50 HYBRID,COMPACT,3.5,6,AS7,Z,8.2,6.7,7.5,38,172.0
528,INFINITI,Q50 HYBRID,COMPACT,3.5,6,AS7,Z,8.2,6.7,7.5,38,172.0
13,ASTON MARTIN,DB9,MINICOMPACT,5.9,12,A6,Z,18.0,12.6,15.6,18,NaN

 **Q. 15 Which vehicle has the highest fuel efficiency (km/L) based on the given dataset?**

In [30]:
# Add a new column for fuel efficiency (km per liter)
data =  data.assign(Fuel_Efficiency=data['Fuel Consumption Comb (L/100 km)'] * 100)

# Find the vehicle with the highest fuel efficiency
max_efficiency_vehicle = data[data['Fuel_Efficiency'] == data['Fuel_Efficiency'].max()]
max_efficiency_vehicle

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km),Fuel_Efficiency
1329,CHEVROLET,EXPRESS 3500 PASSENGER FFV,VAN - PASSENGER,6.0,8,A6,E,30.6,20.6,26.1,11,418.0,2610.0
1534,GMC,SAVANA 3500 PASSENGER FFV,VAN - PASSENGER,6.0,8,A6,E,30.6,20.6,26.1,11,418.0,2610.0

# End!